"""
Markdown report generation.

Assembles the outputs of a pipeline run (data quality, segmentation,
modeling, evaluation, fairness) into a single human-readable report under
`reports/`, with the same honesty-first framing as the EDA notebook.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

from src.config import Config


def build_report(
    cfg: Config,
    n_rows: int,
    missingness: pd.Series,
    cv_results: pd.DataFrame,
    best_model_name: str,
    test_metrics: dict,
    cost_result: dict,
    fairness_table: pd.DataFrame,
    segmentation_k: int,
    segmentation_silhouette: float,
) -> str:
    target_mode = cfg.get("target", "mode")
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    cr = test_metrics["classification_report"]
    disparate_impact = fairness_table.attrs.get("disparate_impact_ratio")
    flag_review = fairness_table.attrs.get("flag_for_review")

    lines = [
        "# German Credit Risk — Pipeline Run Report",
        f"_Generated: {timestamp}_",
        "",
        "## ⚠️ Target variable caveat",
        f"`target.mode = \"{target_mode}\"`. " + (
            "**This run used the heuristic PROXY target** — every metric below "
            "reflects pipeline correctness on a self-constructed score, not "
            "real-world credit risk performance. See `src/proxy_scoring.py` "
            "and the README for the full caveat."
            if target_mode == "proxy" else
            "This run used a real label column — metrics below are genuine "
            "out-of-sample performance estimates, subject to the usual caveats "
            "about sample size and validation design."
        ),
        "",
        "## 1. Data",
        f"- Rows processed: **{n_rows}**",
        "- Missing values by column (post raw load):",
        "",
        missingness.to_frame("missing_count").to_markdown(),
        "",
        "## 2. Unsupervised Segmentation",
        f"- Selected k = **{segmentation_k}** (silhouette score = {segmentation_silhouette:.3f})",
        "- See `reports/figures/` for the PCA projection and elbow/silhouette plots "
        "generated by `notebooks/01_eda_and_methodology.ipynb`.",
        "",
        "## 3. Model Comparison (5-fold stratified cross-validation, training set)",
        "",
        cv_results.round(3).to_markdown(index=False),
        "",
        f"**Selected model:** {best_model_name} (highest mean {cfg['modeling']['primary_metric']})",
        "",
        "## 4. Held-Out Test Performance",
        f"- ROC-AUC: **{test_metrics['roc_auc']:.3f}**",
        f"- PR-AUC (average precision): **{test_metrics['pr_auc']:.3f}**",
        f"- Brier score (lower is better calibrated): **{test_metrics['brier_score']:.3f}**",
        f"- Accuracy: {cr['accuracy']:.3f} | "
        f"Macro F1: {cr['macro avg']['f1-score']:.3f}",
        "",
        "Diagnostic plots: `reports/figures/diagnostic_curves.png`, "
        "`reports/figures/confusion_matrix.png`, `reports/figures/feature_importance.png`",
        "",
        "## 5. Cost-Sensitive Threshold Optimization",
        f"- Cost matrix: {cfg['cost_sensitive']['false_negative_cost']}× cost per false "
        f"negative, {cfg['cost_sensitive']['false_positive_cost']}× cost per false positive",
        f"- Default threshold (0.50) expected cost: **{cost_result['default_cost']:.0f}**",
        f"- Cost-optimal threshold ({cost_result['optimal_threshold']:.2f}) expected cost: "
        f"**{cost_result['optimal_cost']:.0f}**",
        f"- Improvement: **{cost_result['pct_cost_improvement']:.1f}%**",
        "",
        "See `reports/figures/cost_threshold_curve.png`.",
        "",
        "## 6. Fairness Audit (by `Sex`, excluded from model features)",
        "",
        fairness_table.to_markdown(),
        "",
    ]
    if disparate_impact is not None:
        lines.append(
            f"- Disparate impact ratio (min/max flagged-high-risk rate): "
            f"**{disparate_impact:.2f}** — "
            + ("⚠️ below the conventional 0.8 review threshold; investigate further."
               if flag_review else "within the conventional 0.8 review threshold.")
        )
    lines += [
        "",
        "## 7. Limitations (restated)",
        "1. No ground-truth default label was available in the source data (see caveat above).",
        "2. The proxy score's weights are documented judgment calls, not fit to any outcome.",
        "3. Small, single-snapshot sample (n≈1,000); no temporal validation possible.",
        "4. Missing-value treatment ('no account') is statistically supported but not "
        "confirmed against the data owner.",
        "5. Fairness audit covers a single attribute and is not a substitute for a full "
        "disparate-impact study.",
        "",
        "Full narrative analysis: `notebooks/01_eda_and_methodology.ipynb`.",
    ]
    return "\n".join(lines)


def save_report(report_text: str, cfg: Config) -> Path:
    out_path = cfg.path("reports_dir") / "pipeline_run_report.md"
    out_path.write_text(report_text)
    return out_path
